apiVersion: identity.vault.upbound.io/v1alpha1
kind: GroupPolicies
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/grouppolicies
  labels:
    testing.upbound.io/example-name: policies
  name: policies
spec:
  forProvider:
    exclusive: true
    groupId: ${vault_identity_group.internal.id}
    policies:
    - default
    - test

---

apiVersion: identity.vault.upbound.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/grouppolicies
  labels:
    testing.upbound.io/example-name: internal
  name: internal
spec:
  forProvider:
    externalPolicies: true
    metadata:
      version: "2"
    name: internal
    type: internal
