apiVersion: aws.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/authbackendrole
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    authType: ec2
    backend: cert
    bound_account_id: "123456789012"
    policies:
    - dev
    - prod
    - qa
    - test
    role: '%s'
    roleTag: VaultRoleTag

---

apiVersion: auth.vault.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/authbackendrole
  labels:
    testing.upbound.io/example-name: aws
  name: aws
spec:
  forProvider:
    path: '%s'
    type: aws

---

