apiVersion: aws.vault.upbound.io/v1alpha1
kind: AuthBackendRoletagBlacklist
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/authbackendroletagblacklist
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    backend: cert
    safetyBuffer: 360

---

apiVersion: auth.vault.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/authbackendroletagblacklist
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    type: aws
