apiVersion: aws.vault.upbound.io/v1alpha1
kind: AuthBackendLogin
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/authbackendlogin
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    backend: cert
    identity: BASE64ENCODEDIDENTITYDOCUMENT
    role: test-role
    signature: BASE64ENCODEDSHA256IDENTITYDOCUMENTSIGNATURE

---

apiVersion: auth.vault.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/authbackendlogin
  labels:
    testing.upbound.io/example-name: aws
  name: aws
spec:
  forProvider:
    path: aws
    type: aws

---

apiVersion: aws.vault.upbound.io/v1alpha1
kind: AuthBackendClient
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/authbackendlogin
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accessKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    backend: aws
    secretKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system

---

apiVersion: aws.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/authbackendlogin
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    authType: ec2
    backend: aws
    bound_account_id: "123456789012"
    bound_ami_id: ami-8c1be5f6
    bound_subnet_id: vpc-133128f1
    bound_vpc_id: vpc-b61106d4
    boundIamInstanceProfileArns:
    - arn:aws:iam::123456789012:instance-profile/MyProfile
    max_ttl: 120
    role: test-role
    tokenPolicies:
    - default
    - dev
    - prod
    ttl: 60
