apiVersion: approle.vault.upbound.io/v1alpha1
kind: AuthBackendRoleSecretID
metadata:
  annotations:
    meta.upbound.io/example-id: approle/v1alpha1/authbackendrolesecretid
  labels:
    testing.upbound.io/example-name: id
  name: id
spec:
  forProvider:
    backend: cert
    metadata: |-
      ${jsonencode(
          {
            "hello" = "world"
          }
        )}
    roleName: ${vault_approle_auth_backend_role.example.role_name}

---

apiVersion: approle.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: approle/v1alpha1/authbackendrolesecretid
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    backend: ${vault_auth_backend.approle.path}
    roleName: test-role
    tokenPolicies:
    - default
    - dev
    - prod

---

apiVersion: auth.vault.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: approle/v1alpha1/authbackendrolesecretid
  labels:
    testing.upbound.io/example-name: approle
  name: approle
spec:
  forProvider:
    type: approle
