apiVersion: pki.vault.upbound.io/v1alpha1
kind: SecretBackendIntermediateCertRequest
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1alpha1/secretbackendintermediatecertrequest
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    backend: dummy
    commonName: app.my.domain
    type: internal
