apiVersion: pki.vault.upbound.io/v1alpha1
kind: SecretBackendCert
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1alpha1/secretbackendcert
  labels:
    testing.upbound.io/example-name: app
  name: app
spec:
  forProvider:
    backend: dummy
    commonName: app.my.domain
    name: my_role
